`63070501061 S.RAKNA`

> 4 hr.

# Code Naive Bayes from Scratch
- Write a program to read the *Iris* dataset, 
- split into 2 parts: training and testing just like it was done in the example. 
- Then write your own code to:

In [4]:
from sklearn.datasets import load_iris
the_data = load_iris()  # get the data from sklearn
label_name = the_data['target_names']
feature_name = the_data['feature_names']
labels = the_data['target']
features = the_data['data']

In [5]:
print("\n the_data data type: ", type(the_data))
print("Feature Names: \n", feature_name)
print("\nTarget Label Names: \n", label_name)
print("\nfeatures data type: ", type(features))
print("\nAll Features in the data: \n", features)
print("\nAll Labels in the data: \n", labels)


 the_data data type:  <class 'sklearn.utils._bunch.Bunch'>
Feature Names: 
 ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

Target Label Names: 
 ['setosa' 'versicolor' 'virginica']

features data type:  <class 'numpy.ndarray'>

All Features in the data: 
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4

In [6]:
# split 70:30
from sklearn.model_selection import train_test_split
# Spliting our dataset into 2 parts for training and testing
training_features, testing_features, training_labels, testing_labels = train_test_split(
    features, labels, test_size=0.2, random_state=0)
print("\nTraining features: \n", training_features)
print("\nTraining Labels: \n", training_labels)
print("\nTesting Labels: \n", testing_labels)


Training features: 
 [[6.4 3.1 5.5 1.8]
 [5.4 3.  4.5 1.5]
 [5.2 3.5 1.5 0.2]
 [6.1 3.  4.9 1.8]
 [6.4 2.8 5.6 2.2]
 [5.2 2.7 3.9 1.4]
 [5.7 3.8 1.7 0.3]
 [6.  2.7 5.1 1.6]
 [5.9 3.  4.2 1.5]
 [5.8 2.6 4.  1.2]
 [6.8 3.  5.5 2.1]
 [4.7 3.2 1.3 0.2]
 [6.9 3.1 5.1 2.3]
 [5.  3.5 1.6 0.6]
 [5.4 3.7 1.5 0.2]
 [5.  2.  3.5 1. ]
 [6.5 3.  5.5 1.8]
 [6.7 3.3 5.7 2.5]
 [6.  2.2 5.  1.5]
 [6.7 2.5 5.8 1.8]
 [5.6 2.5 3.9 1.1]
 [7.7 3.  6.1 2.3]
 [6.3 3.3 4.7 1.6]
 [5.5 2.4 3.8 1.1]
 [6.3 2.7 4.9 1.8]
 [6.3 2.8 5.1 1.5]
 [4.9 2.5 4.5 1.7]
 [6.3 2.5 5.  1.9]
 [7.  3.2 4.7 1.4]
 [6.5 3.  5.2 2. ]
 [6.  3.4 4.5 1.6]
 [4.8 3.1 1.6 0.2]
 [5.8 2.7 5.1 1.9]
 [5.6 2.7 4.2 1.3]
 [5.6 2.9 3.6 1.3]
 [5.5 2.5 4.  1.3]
 [6.1 3.  4.6 1.4]
 [7.2 3.2 6.  1.8]
 [5.3 3.7 1.5 0.2]
 [4.3 3.  1.1 0.1]
 [6.4 2.7 5.3 1.9]
 [5.7 3.  4.2 1.2]
 [5.4 3.4 1.7 0.2]
 [5.7 4.4 1.5 0.4]
 [6.9 3.1 4.9 1.5]
 [4.6 3.1 1.5 0.2]
 [5.9 3.  5.1 1.8]
 [5.1 2.5 3.  1.1]
 [4.6 3.4 1.4 0.3]
 [6.2 2.2 4.5 1.5]
 [7.2 3.6 6.1 2.5]
 [5.7 2.9

> 5 pts. 

#### a

- Find the **mean** and **standard deviation** for each of the 4 features of each of the 3 classes from the training data. 
- $μ_{ik}$ and $σ_{ik}$ for $i = 1..4, k = 1..3$ 
- You will get pdfs $P(x_i | c_k)$ for each class using the Gaussian distribution equation with $μ_{ik}$ and $σ_{ik}$ for $i = 1..4, k = 1..3$. 
- This gets you pdfs: $P(x_1, x_2, x_3, x_4 | c_1), P(x_1, x_2, x_3, x_4 | c_2), P(x_1, x_2, x_3, x_4 | c_3)$

In [7]:
import numpy as np

In [8]:
means = {}
stds = {}
for label in np.unique(training_labels):
    means[label] = np.mean(training_features[training_labels == label], axis=0)
    stds[label] = np.std(training_features[training_labels == label], axis=0)

In [9]:
# print index of the label and name of the label
for i, label in enumerate(label_name):
    print("Label: ", i, " Name: ", label)
print("\nMeans: \n", means)
print("\nStds: \n", stds)

Label:  0  Name:  setosa
Label:  1  Name:  versicolor
Label:  2  Name:  virginica

Means: 
 {0: array([5.02051282, 3.4025641 , 1.46153846, 0.24102564]), 1: array([5.88648649, 2.76216216, 4.21621622, 1.32432432]), 2: array([6.63863636, 2.98863636, 5.56590909, 2.03181818])}

Stds: 
 {0: array([0.35961481, 0.37654787, 0.14253274, 0.10553393]), 1: array([0.51368418, 0.32244954, 0.47959077, 0.20189026]), 2: array([0.62385018, 0.3283678 , 0.54269663, 0.25385458])}


> 5 pts. 

#### b

Find the $P(c_k)$ by counting the percent frequency of each class in your training data. 
Now we have $P(c_k | x_1, x_2, x_3, x_4) ∝ P(x_1, x_2, x_3, x_4 | c_k) * P(c_k)$

In [10]:
# calculate the probability of a label
prob = {}
for label in np.unique(training_labels):
    prob[label] = np.mean(training_labels == label)
print("\nProp: \n", prob)


Prop: 
 {0: 0.325, 1: 0.30833333333333335, 2: 0.36666666666666664}


> 5 pts. 

#### c

Then for each $(x_1, x_2, x_3, x_4)$ in your test data: find the class $k$ of $1, 2, $ or $3$ for which $P(c_k | x_1, x_2, x_3, x_4)$ is maximum, put that $k$ into array `my_predicted_labels`

In [11]:
my_predicted_labels = []
for feature in testing_features:
    # calculate the probability of each label
    probs = {}
    for label in np.unique(training_labels):
        probs[label] = np.prod(np.exp(-(feature - means[label])**2 / (
            2 * stds[label]**2)) / (np.sqrt(2 * np.pi) * stds[label])) * prob[label]

    # get the label with the highest probability
    my_predicted_labels.append(max(probs, key=probs.get)) # type: ignore


In [12]:
print("\nMy Predicted Labels: \n", my_predicted_labels)


My Predicted Labels: 
 [2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1, 0, 0, 2, 0, 0, 1, 1, 0]


> 5 pts. 

#### d

Calculate and print the accuracy score from your implementation of Naive Bayes from scratch

In [13]:
accuracy = np.where(my_predicted_labels == testing_labels,
                    1, 0).sum() / len(testing_labels)
print("\nAccuracy: ", accuracy)



Accuracy:  0.9666666666666667
